name: Build and Test
on:
  pull_request:
    branches: 'main'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn test:typecheck

      - uses: actions/upload-artifact@v3.1.1
        if: success()
        with:
          name: '${{ github.job }}'
          path: dist
